import express from 'express';
import cors from 'cors';
import sqlite3 from 'sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';

const app = express();
// Use port 5000 inside the container
const PORT = 5000;

// ES Module setup for paths
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbPath = path.resolve(__dirname, '../db/database.sqlite');
const frontendPath = path.resolve(__dirname, '../public_html');

// Middleware
app.use(cors());
app.use(express.json());

// 1. Database Connection & Initialization
const db = new sqlite3.Database(dbPath, (err) => {
    if (err) {
        console.error("Database connection error:", err.message);
    } else {
        console.log("Connected to SQLite database.");
        // Create table using English column names
        db.run(`CREATE TABLE IF NOT EXISTS submissions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL,
            age INTEGER,
            date TEXT,
            subscribe INTEGER,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )`);
    }
});

// 2. API ROUTES

// POST: Save form data to database
app.post('/api/submit', (req, res) => {
    const { name, email, age, date, subscribe } = req.body;
    
    const sql = `INSERT INTO submissions (name, email, age, date, subscribe) VALUES (?, ?, ?, ?, ?)`;
    const params = [name, email, age, date, subscribe ? 1 : 0];

    db.run(sql, params, function(err) {
        if (err) {
            console.error("Database error:", err.message);
            return res.status(500).json({ error: "Failed to save data to database." });
        }
        res.json({ 
            message: "Data saved successfully!", 
            id: this.lastID 
        });
    });
});

// GET: Retrieve all submissions (For the 2-point requirement)
app.get('/api/submissions', (req, res) => {
    const sql = "SELECT * FROM submissions ORDER BY created_at DESC";
    db.all(sql, [], (err, rows) => {
        if (err) {
            console.error("Database error:", err.message);
            return res.status(500).json({ error: "Failed to retrieve data." });
        }
        res.json(rows);
    });
});

// 3. Serve Static Frontend Files (For Docker Integration)
// This serves the 'dist' folder generated by Vite
app.use(express.static(frontendPath));

// 4. SPA Routing
// Ensures that refreshing the page on a React route doesn't give a 404
app.get('*', (req, res) => {
    res.sendFile(path.join(frontendPath, 'index.html'));
});

app.listen(PORT, () => {
    console.log(`Server is running on http://localhost:${PORT}`);
    console.log(`Serving frontend from: ${frontendPath}`);
});